# Generated by Django 2.0.13 on 2019-10-23 18:43

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_customimage_alt_text'),
        ('blog', '0003_auto_20190924_0127'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='welcome_quote',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='welcome_quote_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_welcome_quote_img', to='images.CustomImage'),
        ),
    ]
