# Generated by Django 2.0.13 on 2019-05-16 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_banner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.CustomImage'),
        ),
    ]
