# Generated by Django 2.0.13 on 2019-10-23 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_customimage_alt_text'),
        ('home', '0002_homepage_hero_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='welcome_quote_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='welcome_quote_img', to='images.CustomImage'),
        ),
    ]
