# Generated by Django 2.0.13 on 2019-09-24 01:54

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('subheading', models.CharField(blank=True, max_length=250)),
                ('about_text', wagtail.core.fields.RichTextField(blank=True)),
                ('about_image', models.ImageField(blank=True, upload_to='homepage')),
                ('hero_banner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.CustomImage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
